//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Apps_Lectures03_Preformance
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int WorkHoursLogsId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<System.DateTime> OldTaskDate { get; set; }
        public string OldTask { get; set; }
        public Nullable<short> OldHours { get; set; }
        public string OldComments { get; set; }
        public Nullable<System.DateTime> NewTaskDate { get; set; }
        public string NewTask { get; set; }
        public Nullable<short> NewHours { get; set; }
        public string NewComments { get; set; }
        public string Command { get; set; }
    }
}
