//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problem03.WorkingWithDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public Homework()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public int ContentType { get; set; }
        public Nullable<int> Course_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
