//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problem03.WorkingWithDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime RegstrationDate { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Homework_Id { get; set; }
    
        public virtual Homework Homework { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
